### ISSUE TITLE
Traefik Image version referenced in deployment.yaml , and Kubernetes support otdated

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [dusansusic/kubernetes-traefik#10]
* Your recipe provisions a Traefik v2..x
* But you still use, in the configuration map, a traefik config, that is [deprecated since traefik 1.7](https://github.com/containous/traefik/pull/5119), this : 

```Yaml
    [api]
    entryPoint = "traefik"
```

So I really do not understand. Is there a way to make your recipe actually work ? 

Note the error message, very well reported in containous/traefik repo : 

```bash 
$ kubectl logs -f service/traefik-ingress-controller-http-service -n traefik
Found 2 pods, using pod/traefik-ingress-controller-7c9bb644cc-4jxgl
2020/05/09 13:39:38 command traefik error: field not found, node: entryPoint

```

**Comment by Jean-Baptiste-Lasselle** [comment]
@dusansusic Ok, I found what explained the configration incompatibility , in your `deployment.yaml` you rely on latest, which changes trhough tile, so your recipe is out of date :

```Yaml
      containers:
      # - image: traefik
      - image: traefik:v1.7
        name: traefik-ingress-controller
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 384Mi
```

* Then using this port forward, you can access traefik webui through proxy : 

```bash 
kubectl port-forward service/traefik-ingress-controller-dashboard-service 8088:8080 -n traefik
```

* then access traefik web ui at http://127.0..1:8088/
